name: 'Test action'
description: 'Test action'
author: 'Donovan'
inputs:
  aws_s3_bucket:
    required: true
    description: Aws bucket
    default: 'attraqt-io-ssl-certificates'
  aws_s3_region:
    required: true
    description: Aws bucket
    default: 'eu-west-1'
  github_token:
    required: true
    description: 'Your github token used to commit updates'
runs:
  using: 'node12'
  main: 'dist/index.js'
